name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install proto
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        
      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install proto
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
          
      - name: Check formatting
        run: cargo fmt --all -- --check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install proto
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        
      - name: Build workspace
        run: cargo build --workspace --all-targets --all-features

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install proto
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        
      - name: Run tests
        run: cargo test --workspace --all-features

  moon-check:
    name: Moon Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      
      - name: Run moon check
        run: moon check --all